# SPDX-License-Identifier: Apache-2.0
# Disabled: Inherited from upstream, not applicable to Goliath fork
name: "Build Image Test"
on:
  workflow_dispatch:
jobs:
  disabled:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is disabled"
